name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
sort-direction: ascending

categories:
  - title: "Breaking Changes"
    labels:
      - "breaking-change"
  - title: "New Features"
    labels:
      - "enhancement"
      - "feature"
  - title: "Bug Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "Documentation"
    labels:
      - "documentation"
  - title: "Maintenance"
    labels:
      - "maintenance"
      - "dependencies"
      - "chore"

version-resolver:
  major:
    labels:
      - "breaking-change"
  minor:
    labels:
      - "enhancement"
      - "feature"
  patch:
    labels:
      - "bug"
      - "fix"
      - "maintenance"
      - "dependencies"
      - "chore"
      - "documentation"
  default: patch

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
