name: Deploy

on:
  push:
    branches:
      - main
  release:
    types:
      - published

permissions: {}

jobs:
  ci:
    permissions:
      actions: read
      contents: read
      packages: read
      security-events: write
    uses: hassos-apps/workflows/.github/workflows/app-ci.yaml@main
    with:
      addon: "__APP_SLUG__"

  deploy:
    needs: ci
    permissions:
      contents: read
      packages: write
    uses: hassos-apps/workflows/.github/workflows/app-deploy.yaml@main
    with:
      addon: "__APP_SLUG__"
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
